SELECT 
    A.ITEM_ID, I.ITEM_NAME, I.RARITY 
FROM 
    ITEM_TREE A 
LEFT JOIN 
    ITEM_TREE B 
ON A.ITEM_ID = B.PARENT_ITEM_ID 

JOIN 
    ITEM_INFO I 
ON A.ITEM_ID = I.ITEM_ID 
WHERE 
    B.PARENT_ITEM_ID IS NULL 
ORDER BY 
    1 DESC 