WITH D AS (
    SELECT 
        HISTORY_ID, DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) DATE_FEE, C.CAR_TYPE CAR_TYPE, 
        CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상' 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상' 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' 
        END AS DURATION_TYPE 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
    JOIN CAR_RENTAL_COMPANY_CAR C 
    ON H.CAR_ID = C.CAR_ID 
    WHERE CAR_TYPE = '트럭' 
)

SELECT HISTORY_ID, ROUND(DATE_FEE - (DATE_FEE * (IFNULL(DISCOUNT_RATE, 0)/100.0))) FEE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
RIGHT JOIN D D 
ON P.DURATION_TYPE = D.DURATION_TYPE 
AND P.CAR_TYPE = D.CAR_TYPE 
ORDER BY FEE DESC, HISTORY_ID DESC 