SELECT 
    CONCAT('/home/grep/src/', M.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH 
FROM USED_GOODS_FILE F 
JOIN (SELECT BOARD_ID FROM USED_GOODS_BOARD WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)) M
ON F.BOARD_ID = M.BOARD_ID 
ORDER BY FILE_ID DESC;