WITH MAX_FISH AS (
    SELECT FISH_NAME, MAX(LENGTH) LENGTH
    FROM FISH_INFO I 
    JOIN FISH_NAME_INFO N 
    ON I.FISH_TYPE = N.FISH_TYPE 
    GROUP BY FISH_NAME 
)

SELECT I.ID, N.FISH_NAME, M.LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N 
ON I.FISH_TYPE = N.FISH_TYPE 
JOIN MAX_FISH M 
ON N.FISH_NAME = M.FISH_NAME AND I.LENGTH = M.LENGTH 
ORDER BY 1