WITH RECURSIVE GENER AS ( 
    SELECT ID, PARENT_ID, 1 AS GENERATION 
    FROM ECOLI_DATA 
    WHERE PARENT_ID IS NULL 
    
    UNION ALL 
    
    SELECT E.ID, E.PARENT_ID, GENERATION+1 AS GENERATION 
    FROM GENER G INNER JOIN ECOLI_DATA E 
    ON G.ID = E.PARENT_ID 
) 

SELECT COUNT(G.ID) COUNT, GENERATION 
FROM GENER G LEFT JOIN ECOLI_DATA E 
ON G.ID = E.PARENT_ID  
WHERE E.PARENT_ID IS NULL 
GROUP BY 2 
ORDER BY 2 