WITH RECURSIVE GENER AS(
    SELECT ID, PARENT_ID, 1 AS GEN 
    FROM ECOLI_DATA WHERE PARENT_ID IS NULL 
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, GEN + 1 AS GEN
    FROM GENER G INNER JOIN ECOLI_DATA E
    WHERE G.ID = E.PARENT_ID 
)

SELECT ID 
FROM GENER 
WHERE GEN = 3 
ORDER BY ID 