# 풀이 1
SELECT  CONCAT(QUARTER(DIFFERENTIATION_DATE), 'Q') as QUARTER,
        COUNT(id) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 1
ORDER BY 1

# 풀이 2
SELECT  CASE
        WHEN MONTH(DIFFERENTIATION_DATE) <= 3 THEN '1Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 6 THEN '2Q'
        WHEN MONTH(DIFFERENTIATION_DATE) <= 9 THEN '3Q'
        ELSE '4Q'
        END as QUARTER,
        COUNT(id) as ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY 1
ORDER BY 1