WITH CODE_SUM AS (
    SELECT
    (SELECT SUM(CODE) CODE FROM SKILLCODES WHERE CATEGORY = 'Front End') FRONT, 
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') PYTHON,
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') C 
),

T AS (
    SELECT 
        CASE
    WHEN SKILL_CODE & CODE_SUM.FRONT > 0 AND SKILL_CODE & CODE_SUM.PYTHON > 0 THEN 'A' 
    WHEN SKILL_CODE & CODE_SUM.C > 0 THEN 'B' 
    WHEN SKILL_CODE & CODE_SUM.PYTHON > 0 THEN 'C' 
    END AS GRADE,
    ID, EMAIL 
    FROM DEVELOPERS D
    JOIN CODE_SUM 
    ORDER BY GRADE, ID 
)

SELECT 
    * 
FROM T 
WHERE GRADE IS NOT NULL