WITH AVG_GRADE AS (
    SELECT EMP_NO, AVG(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT 
    a.EMP_NO, 
    EMP_NAME, 
    CASE 
    WHEN SCORE >= 96 THEN 'S'
    WHEN SCORE >= 90 THEN 'A'
    WHEN SCORE >= 80 THEN 'B'
    ELSE 'C'
    END AS GRADE, 
    CASE 
    WHEN SCORE >= 96 THEN SAL * 0.2
    WHEN SCORE >= 90 THEN SAL * 0.15
    WHEN SCORE >= 80 THEN SAL * 0.1
    ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES h 
JOIN AVG_GRADE a 
ON h.EMP_NO = a.EMP_NO
ORDER BY EMP_NO