WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    UNION ALL
        SELECT HOUR + 1 FROM CTE
        WHERE HOUR < 23
)

SELECT c.HOUR, COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS a
RIGHT JOIN CTE c
ON HOUR(a.DATETIME) = c.HOUR
GROUP BY HOUR
ORDER BY HOUR