SELECT 
    a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM 
    BOOK b JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
    JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
    WHERE s.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY 
    AUTHOR_ID,
    CATEGORY DESC