WITH TOP AS (
    SELECT SUM(SCORE) SCORE, EMP_NO 
    FROM HR_GRADE 
    GROUP BY EMP_NO 
    ORDER BY SCORE DESC 
    LIMIT 1
)

SELECT t.SCORE, t.EMP_NO, EMP_NAME, POSITION, EMAIL 
FROM HR_EMPLOYEES h JOIN TOP t 
ON h.EMP_NO = t.EMP_NO