SELECT 
    P.PRODUCT_ID, PRODUCT_NAME, SUM(AMOUNT) * PRICE TOTAL_SALES 
FROM 
    FOOD_PRODUCT P JOIN FOOD_ORDER O 
    ON 
    P.PRODUCT_ID = O.PRODUCT_ID 
WHERE 
    LEFT(PRODUCE_DATE, 7) = '2022-05' 
GROUP BY 
    P.PRODUCT_ID 
ORDER BY 
    3 DESC, 1 