WITH FRONTEND AS (
    SELECT CODE  
    FROM SKILLCODES
    WHERE CATEGORY = 'FRONT END'
)

SELECT 
    DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME 
FROM 
    DEVELOPERS D 
JOIN 
    FRONTEND F 
ON D.SKILL_CODE & F.CODE 
ORDER BY 
    ID