SELECT 
    MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE 
FROM 
    MEMBER_PROFILE M LEFT JOIN REST_REVIEW R 
    ON 
    R.MEMBER_ID = M.MEMBER_ID 
WHERE 
    M.MEMBER_ID = (
        SELECT MEMBER_ID FROM REST_REVIEW 
        GROUP BY MEMBER_ID 
        ORDER BY COUNT(MEMBER_ID) DESC 
        LIMIT 1 
    ) 
ORDER BY 
    REVIEW_DATE, 
    REVIEW_TEXT 