SELECT F.FLAVOR 
FROM FIRST_HALF F 
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL 
    FROM JULY 
    GROUP BY FLAVOR 
) J 
ON F.FLAVOR = J.FLAVOR 
GROUP BY FLAVOR 
ORDER BY SUM(TOTAL_ORDER + TOTAL) DESC
LIMIT 3 