WITH AVAILABLE_CAR AS (
    SELECT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' 
)
    
SELECT CAR_ID, P.CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE)/100 * 30) AS FEE 
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN P 
JOIN CAR_RENTAL_COMPANY_CAR R
ON P.CAR_TYPE = R.CAR_TYPE 
WHERE P.DURATION_TYPE = '30일 이상' AND R.CAR_TYPE IN ('SUV', '세단') AND CAR_ID NOT IN (SELECT CAR_ID FROM AVAILABLE_CAR) AND DAILY_FEE * (100 - DISCOUNT_RATE)/100 * 30 BETWEEN 500000 AND 2000000
ORDER BY 
    3 DESC, 
    2, 
    1 DESC;